### ISSUE TITLE
Setup Flutter/Flame Project Infrastructure

### ISSUE THREAD

**Issue by eatingbug** [eatingbug/eco-heroes#12]
**Labels**: epic, infrastructure, sprint-1
**Assignee**: Dev A  
**Story Points**: 8

**Description:**
Set up the basic Flutter/Flame project structure with proper architecture

**Acceptance Criteria:**
- [ ] Create Flutter project with Flame engine v1.29.0
- [ ] Set up overlay navigation system
- [ ] Implement base game class (`EcoHeros`)
- [ ] Create folder structure matching specification
- [ ] Add required dependencies (flame, camera, audioplayers)
- [ ] Configure pubspec.yaml with asset directories

**Technical Notes:**
- Follow hybrid Flutter + Flame architecture
- Use overlay system for screen management
- Ensure proper GameWidget setup in main.dart

**Dependencies Required:**
```yaml
dependencies:
  flutter:
    sdk: flutter
  flame: ^1.29.0
  camera: ^0.10.5
  audioplayers: ^5.0.0
  
dev_dependencies:
  flutter_lints: ^5.0.0
```

**Folder Structure:**
```
lib/
├── main.dart                    # Entry point with GameWidget setup
├── eco_heros.dart              # Main game class (extends Flame Game)
├── screens/
│   ├── intro_screen.dart       # Animated introduction
│   ├── main_screen.dart        # Main menu hub
│   └── mini_games/
│       ├── eco_sort_game.dart  # Recycling game
│       ├── clean_plate_game.dart # Food waste game
│       └── ocean_rescue_game.dart # Ocean cleanup game
├── calendar_screen.dart        # Environmental calendar
└── ai_helper_screen.dart       # AI assistant feature
```
